version: '3.4'

services:
  ruisantos.labs.localstack:
    image: "localstack/localstack"
    restart: always
    ports:
      - "4566:4566"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DYNAMODB_SHARE_DB=1
      - SERVICES=dynamodb:4569
      - DEFAULT_REGION=us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/private${TMPDIR}:/tmp/localstack"

  ruisantos.labs.api:
    image: ${DOCKER_REGISTRY-}ruisantos.labs.api
    depends_on:
      - ruisantos.labs.localstack
    environment:
      - AWS_ACCESS_KEY_ID=docker
      - AWS_SECRET_ACCESS_KEY=docker
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://ruisantos.labs.localstack:4566
      - LABS_ALLOWED_ORIGINS=http://localhost:8002
    ports:
      - 8001:80
    build:
      context: .
      dockerfile: ./Dockerfile
  
  ruisantos.labs.client:
    image: ${DOCKER_REGISTRY-}ruisantos.labs.client
    depends_on:
      - ruisantos.labs.api
    ports:
      - 8002:80
    build:
      context: ./Server/RuiSantos.Labs.Client
      dockerfile: ./Dockerfile 