version: '3.4'

services:
  ruisantos.labs.db.dynamo:
   command: "-jar DynamoDBLocal.jar -sharedDb"
   image: "amazon/dynamodb-local:latest"
   restart: always
   ports:
     - "8000:8000"

  ruisantos.labs.api:
    image: ${DOCKER_REGISTRY-}ruisantos.labs.api
    depends_on:
      - ruisantos.labs.db.dynamo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_DYNAMO=http://ruisantos.labs.db.dynamo:8000
    ports:
      - 8001:80
    build:
      context: .
      dockerfile: ./Dockerfile
  
  ruisantos.labs.client:
    image: ${DOCKER_REGISTRY-}ruisantos.labs.client
    depends_on:
      - ruisantos.labs.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RUISANTOS_LABS_API_URL=http://localhost:8001/graphql/
    ports:
      - 8002:80
    build:
      context: ./Server/RuiSantos.Labs.Client
      dockerfile: ./Dockerfile 