name: .NET 9 API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      Solution_Name: RuiSantos.Labs.sln
      Test_Project_Name: Tests/RuiSantos.Labs.Tests/RuiSantos.Labs.Tests.csproj
      
    steps:
    
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore $Solution_Name
          
    - name: Build
      run: dotnet build --no-restore $Solution_Name

    - name: Unit Tests
      run: dotnet test --no-build --nologo --verbosity normal $Test_Project_Name